/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

//import BEAN.cliente_lsmc;
//import DAO.clienteDAO_lsmc;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author u08652975175
 */
public class JDlgCliente extends javax.swing.JDialog {

    private MaskFormatter mascaraCpf, mascaraRg, mascaraData, mascaraTelefone, mascaraCep, mascaraLicenca;
    
    /**
     * Creates new form JDlgUsuarios
     */
    public JDlgCliente(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Cadastro de Clientes");
        setLocationRelativeTo(null);
//        habilitar(false);
        try {
            mascaraCpf = new MaskFormatter("###.###.###-##");
            mascaraRg = new MaskFormatter("#.###.###");
            mascaraData = new MaskFormatter("##/##/####");
            mascaraTelefone = new MaskFormatter("(##)####-####");
            mascaraCep = new MaskFormatter("#####-###");
            mascaraLicenca = new MaskFormatter("########");
        } catch (ParseException ex) {
            Logger.getLogger(JDlgCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
        jFmtCpf_Lsmc.setFormatterFactory(new DefaultFormatterFactory(mascaraCpf));
        jFmtNascimento_Lsmc.setFormatterFactory(new DefaultFormatterFactory(mascaraData));
        jFmtRg_Lsmc.setFormatterFactory(new DefaultFormatterFactory(mascaraRg));
        jFmtTelefone_Lsmc.setFormatterFactory(new DefaultFormatterFactory(mascaraTelefone));
        jFmtCep_Lsmc.setFormatterFactory(new DefaultFormatterFactory(mascaraCep));
        jFmtLicencaPokemon_Lsmc.setFormatterFactory(new DefaultFormatterFactory(mascaraLicenca));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTxtCodigo_Lsmc = new javax.swing.JTextField();
        jTxtNome_Lsmc = new javax.swing.JTextField();
        jFmtCpf_Lsmc = new javax.swing.JFormattedTextField();
        jFmtNascimento_Lsmc = new javax.swing.JFormattedTextField();
        jLblCodigo = new javax.swing.JLabel();
        jLblNome = new javax.swing.JLabel();
        jLblGenero = new javax.swing.JLabel();
        jLblCpf = new javax.swing.JLabel();
        jLblNascimento = new javax.swing.JLabel();
        jBtnIncluir = new javax.swing.JButton();
        jBtnAlterar = new javax.swing.JButton();
        jBtnExcluir = new javax.swing.JButton();
        jBtnConfirmar = new javax.swing.JButton();
        jBtnCancelar = new javax.swing.JButton();
        jBtnPesquisar = new javax.swing.JButton();
        jLblRg = new javax.swing.JLabel();
        jLblPais = new javax.swing.JLabel();
        jTxtPais_Lsmc = new javax.swing.JTextField();
        jFmtRg_Lsmc = new javax.swing.JFormattedTextField();
        jLblBairro = new javax.swing.JLabel();
        jTxtBairro_Lsmc = new javax.swing.JTextField();
        jLblRua = new javax.swing.JLabel();
        jTxtRua_Lsmc = new javax.swing.JTextField();
        jLblCep = new javax.swing.JLabel();
        jLblNumeroCasa = new javax.swing.JLabel();
        jTxtNumeroCasa_Lsmc = new javax.swing.JTextField();
        jLblEmail = new javax.swing.JLabel();
        jTxtEmail_Lsmc = new javax.swing.JTextField();
        jLblTelefone = new javax.swing.JLabel();
        jFmtCep_Lsmc = new javax.swing.JFormattedTextField();
        jLblLicencaPokemon = new javax.swing.JLabel();
        jLblNivelSatisfacao = new javax.swing.JLabel();
        jLblFeedback = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTxtFeedback_Lsmc = new javax.swing.JTextArea();
        jFmtLicencaPokemon_Lsmc = new javax.swing.JFormattedTextField();
        jFmtTelefone_Lsmc = new javax.swing.JFormattedTextField();
        jCboNivelSatisfacao_Lsmc = new javax.swing.JComboBox<>();
        jCboGenero_lsmc = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLblCodigo.setText("Código");

        jLblNome.setText("Nome");

        jLblGenero.setText("Gênero");

        jLblCpf.setText("CPF");

        jLblNascimento.setText("Nascimento");

        jBtnIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/incluir.png"))); // NOI18N
        jBtnIncluir.setText("Incluir");
        jBtnIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnIncluirActionPerformed(evt);
            }
        });

        jBtnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/alterar.png"))); // NOI18N
        jBtnAlterar.setText("Alterar");
        jBtnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAlterarActionPerformed(evt);
            }
        });

        jBtnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Excluir.png"))); // NOI18N
        jBtnExcluir.setText("Excluir");
        jBtnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExcluirActionPerformed(evt);
            }
        });

        jBtnConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/gravar.png"))); // NOI18N
        jBtnConfirmar.setText("Confirmar");
        jBtnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnConfirmarActionPerformed(evt);
            }
        });

        jBtnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancelar.png"))); // NOI18N
        jBtnCancelar.setText("Cancelar");
        jBtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelarActionPerformed(evt);
            }
        });

        jBtnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pesquisar.png"))); // NOI18N
        jBtnPesquisar.setText("Pesquisar");
        jBtnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPesquisarActionPerformed(evt);
            }
        });

        jLblRg.setText("RG");

        jLblPais.setText("País");

        jLblBairro.setText("Bairro");

        jLblRua.setText("Rua");

        jLblCep.setText("CEP");

        jLblNumeroCasa.setText("Número da Casa");

        jLblEmail.setText("Email");

        jLblTelefone.setText("Telefone");

        jLblLicencaPokemon.setText("Licença Pokemon");

        jLblNivelSatisfacao.setText("Nivel de Satisfação");

        jLblFeedback.setText("Feedback");

        jTxtFeedback_Lsmc.setColumns(20);
        jTxtFeedback_Lsmc.setRows(5);
        jScrollPane1.setViewportView(jTxtFeedback_Lsmc);

        jCboNivelSatisfacao_Lsmc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        jCboGenero_lsmc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Feminino", "Outro" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jBtnIncluir, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBtnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jBtnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnConfirmar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnPesquisar)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLblPais, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLblBairro, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLblRua, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTxtRua_Lsmc, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTxtBairro_Lsmc, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTxtPais_Lsmc, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLblCep)
                                                .addComponent(jFmtCep_Lsmc, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jTxtNumeroCasa_Lsmc, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLblNumeroCasa))))
                                    .addComponent(jLblCpf)
                                    .addComponent(jFmtCpf_Lsmc, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1))
                            .addComponent(jLblGenero))
                        .addGap(6, 6, 6))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLblCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTxtNome_Lsmc, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTxtCodigo_Lsmc, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLblNome))
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jCboGenero_lsmc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jFmtRg_Lsmc, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLblRg)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLblNascimento)
                                        .addComponent(jFmtNascimento_Lsmc, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)))
                                .addGap(28, 28, 28)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxtEmail_Lsmc)
                            .addComponent(jLblNivelSatisfacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLblTelefone)
                                    .addComponent(jLblLicencaPokemon, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLblFeedback)
                                    .addComponent(jFmtLicencaPokemon_Lsmc, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jFmtTelefone_Lsmc, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLblEmail))
                                .addContainerGap())
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jCboNivelSatisfacao_Lsmc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLblCodigo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtCodigo_Lsmc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLblNome)
                            .addComponent(jLblTelefone))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTxtNome_Lsmc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFmtTelefone_Lsmc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLblEmail)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtEmail_Lsmc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLblGenero)
                            .addComponent(jLblLicencaPokemon))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jFmtLicencaPokemon_Lsmc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCboGenero_lsmc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLblNascimento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFmtNascimento_Lsmc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLblNivelSatisfacao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCboNivelSatisfacao_Lsmc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLblFeedback)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLblCpf)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jFmtCpf_Lsmc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLblRg)
                                .addGap(12, 12, 12)
                                .addComponent(jFmtRg_Lsmc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLblPais)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTxtPais_Lsmc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLblBairro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTxtBairro_Lsmc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLblRua)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTxtRua_Lsmc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLblCep)
                            .addComponent(jLblNumeroCasa))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jFmtCep_Lsmc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtNumeroCasa_Lsmc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnConfirmar)
                    .addComponent(jBtnCancelar)
                    .addComponent(jBtnPesquisar)
                    .addComponent(jBtnExcluir)
                    .addComponent(jBtnAlterar)
                    .addComponent(jBtnIncluir))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnIncluirActionPerformed
        habilitar(true);
    }//GEN-LAST:event_jBtnIncluirActionPerformed

    private void jBtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelarActionPerformed
        habilitar(false);
    }//GEN-LAST:event_jBtnCancelarActionPerformed

    private void jBtnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExcluirActionPerformed
//        JOptionPane.showMessageDialog(null, "Exclusão");
//          int resp = JOptionPane.showConfirmDialog(null, "Confirma Exclusão", "Deletar Registro", JOptionPane.YES_NO_OPTION);
//          if (resp == JOptionPane.YES_OPTION){
//            cliente_lsmc cliente = new cliente_lsmc();
//            int cod = Integer.valueOf(jTxtCodigo_Lsmc.getText());
//            cliente.setIdCliente_lsmc(cod);
//            cliente.setNome_lsmc(jTxtNome_Lsmc.getText());
//            cliente.setGenero_lsmc(jCboGenero_lsmc.getSelectedIndex());
//            cliente.setDataNasc_lsmc(null);
//            cliente.setCpf_lsmc(jFmtCpf_Lsmc.getText());
//            cliente.setRg_lsmc(jFmtRg_Lsmc.getText());
//            cliente.setPais_lsmc(jTxtPais_Lsmc.getText());
//            cliente.setBairro_lsmc(jTxtBairro_Lsmc.getText());
//            cliente.setRua_lsmc(jTxtRua_Lsmc.getText());
//            cliente.setCep_lsmc(jFmtCep_Lsmc.getText());
//            cliente.setNumeroCasa_lsmc(jTxtNumeroCasa_Lsmc.getText());
//            cliente.setEmail_lsmc(jTxtEmail_Lsmc.getText());
//            cliente.setTelefone_lsmc(jFmtTelefone_Lsmc.getText());
//            cliente.setLicencaPoke_lsmc(jFmtLicencaPokemon_Lsmc.getText());    
//            cliente.setNivelSatisfacao_lsmc(jCboNivelSatisfacao_Lsmc .getSelectedIndex());
//            cliente.setFeedback_lsmc(jTxtFeedback_Lsmc.getText());
//
//            clienteDAO_lsmc clienteDAO = new clienteDAO_lsmc();
//            clienteDAO.delete(cliente);              
//              
//            JOptionPane.showMessageDialog(null, "Exclusão Ok!");
//            limpar();
//          }
    }//GEN-LAST:event_jBtnExcluirActionPerformed

    private void jBtnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPesquisarActionPerformed
//        String resp = JOptionPane.showInputDialog(null, "Entre com o Código de Cliente");
//        if(resp == null) {
//            JOptionPane.showMessageDialog(null, "Código em branco");
//        } else {
//            clienteDAO_lsmc clienteDAO = new clienteDAO_lsmc();
//            int cod = Integer.valueOf(resp);
//            cliente_lsmc cliente = (cliente_lsmc) clienteDAO.list(cod);
//            String cad = String.valueOf(cliente.getIdCliente_lsmc());
//            jTxtCodigo_Lsmc.setText(cad);
//            jTxtNome_Lsmc.setText(cliente.getNome_lsmc());
//            jCboGenero_lsmc.setSelectedIndex(cliente.getGenero_lsmc());
//            jFmtNascimento_Lsmc.setText(null);
//            jFmtCpf_Lsmc.setText(cliente.getCpf_lsmc());
//            jFmtRg_Lsmc.setText(cliente.getRg_lsmc());
//            jTxtPais_Lsmc.setText(cliente.getPais_lsmc());
//            jTxtBairro_Lsmc.setText(cliente.getBairro_lsmc());
//            jTxtRua_Lsmc.setText(cliente.getRua_lsmc());
//            jFmtCep_Lsmc.setText(cliente.getCep_lsmc());
//            jTxtNumeroCasa_Lsmc.setText(cliente.getNumeroCasa_lsmc());
//            jTxtEmail_Lsmc.setText(cliente.getEmail_lsmc());
//            jFmtTelefone_Lsmc.setText(cliente.getTelefone_lsmc());
//            jFmtLicencaPokemon_Lsmc.setText(cliente.getLicencaPoke_lsmc());
//            jCboNivelSatisfacao_Lsmc.setSelectedIndex(cliente.getNivelSatisfacao_lsmc());
//            jTxtFeedback_Lsmc.setText(cliente.getFeedback_lsmc());
//        }
    }//GEN-LAST:event_jBtnPesquisarActionPerformed

    private void jBtnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnConfirmarActionPerformed
//        cliente_lsmc cliente = new cliente_lsmc();
//        int cod = Integer.valueOf(jTxtCodigo_Lsmc.getText());
//        cliente.setIdCliente_lsmc(cod);
//        cliente.setNome_lsmc(jTxtNome_Lsmc.getText());
//        cliente.setGenero_lsmc(jCboGenero_lsmc.getSelectedIndex());
//        cliente.setDataNasc_lsmc(null);
//        cliente.setCpf_lsmc(jFmtCpf_Lsmc.getText());
//        cliente.setRg_lsmc(jFmtRg_Lsmc.getText());
//        cliente.setPais_lsmc(jTxtPais_Lsmc.getText());
//        cliente.setBairro_lsmc(jTxtBairro_Lsmc.getText());
//        cliente.setRua_lsmc(jTxtRua_Lsmc.getText());
//        cliente.setCep_lsmc(jFmtCep_Lsmc.getText());
//        cliente.setNumeroCasa_lsmc(jTxtNumeroCasa_Lsmc.getText());
//        cliente.setEmail_lsmc(jTxtEmail_Lsmc.getText());
//        cliente.setTelefone_lsmc(jFmtTelefone_Lsmc.getText());
//        cliente.setLicencaPoke_lsmc(jFmtLicencaPokemon_Lsmc.getText());    
//        cliente.setNivelSatisfacao_lsmc(jCboNivelSatisfacao_Lsmc .getSelectedIndex());
//        cliente.setFeedback_lsmc(jTxtFeedback_Lsmc.getText());
//        
//        clienteDAO_lsmc clienteDAO = new clienteDAO_lsmc();
//        clienteDAO.insert(cliente);
//        habilitar(false);
//        
//        JOptionPane.showMessageDialog(null, "Cliente Cadastrado!");
//        limpar();
    }//GEN-LAST:event_jBtnConfirmarActionPerformed

    private void jBtnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAlterarActionPerformed
        JOptionPane.showMessageDialog(null, "Cliente Alterado!");
    }//GEN-LAST:event_jBtnAlterarActionPerformed
    
    private void habilitar(boolean valor){
//        jTxtCodigo_Lsmc.setEnabled(valor);
//        jTxtNome_Lsmc.setEnabled(valor);
//        jCboGenero_lsmc.setEnabled(valor);
//        jFmtCpf_Lsmc.setEnabled(valor);
//        jFmtNascimento_Lsmc.setEnabled(valor);
//        jFmtRg_Lsmc.setEnabled(valor);
//        jFmtCep_Lsmc.setEnabled(valor);
//        jFmtLicencaPokemon_Lsmc.setEnabled(valor);
//        jFmtTelefone_Lsmc.setEnabled(valor);
//        jTxtPais_Lsmc.setEnabled(valor);
//        jTxtBairro_Lsmc.setEnabled(valor);
//        jTxtRua_Lsmc.setEnabled(valor);
//        jTxtNumeroCasa_Lsmc.setEnabled(valor);
//        jTxtEmail_Lsmc.setEnabled(valor);
//        jCboNivelSatisfacao_Lsmc.setEnabled(valor);
//        jTxtFeedback_Lsmc.setEnabled(valor);
//        jBtnCancelar.setEnabled(valor);
//        jBtnConfirmar.setEnabled(valor);
//        
//        jBtnIncluir.setEnabled(!valor);
//        jBtnAlterar.setEnabled(!valor);
//        jBtnExcluir.setEnabled(!valor);
//        jBtnPesquisar.setEnabled(!valor);
    }
    
    public void limpar(){
//        jTxtCodigo_Lsmc.setText("");
//        jTxtNome_Lsmc.setText("");
//        jCboGenero_lsmc.setSelectedIndex(-1);
//        jFmtCpf_Lsmc.setText("");
//        jFmtNascimento_Lsmc.setText("");
//        jFmtRg_Lsmc.setText("");
//        jFmtCep_Lsmc.setText("");
//        jFmtLicencaPokemon_Lsmc.setText("");
//        jFmtTelefone_Lsmc.setText("");
//        jTxtPais_Lsmc.setText("");
//        jTxtBairro_Lsmc.setText("");
//        jTxtRua_Lsmc.setText("");
//        jTxtNumeroCasa_Lsmc.setText("");
//        jTxtEmail_Lsmc.setText("");
//        jCboNivelSatisfacao_Lsmc.setSelectedIndex(-1);
//        jTxtFeedback_Lsmc.setText("");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgCliente dialog = new JDlgCliente(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAlterar;
    private javax.swing.JButton jBtnCancelar;
    private javax.swing.JButton jBtnConfirmar;
    private javax.swing.JButton jBtnExcluir;
    private javax.swing.JButton jBtnIncluir;
    private javax.swing.JButton jBtnPesquisar;
    private javax.swing.JComboBox<String> jCboGenero_lsmc;
    private javax.swing.JComboBox<String> jCboNivelSatisfacao_Lsmc;
    private javax.swing.JFormattedTextField jFmtCep_Lsmc;
    private javax.swing.JFormattedTextField jFmtCpf_Lsmc;
    private javax.swing.JFormattedTextField jFmtLicencaPokemon_Lsmc;
    private javax.swing.JFormattedTextField jFmtNascimento_Lsmc;
    private javax.swing.JFormattedTextField jFmtRg_Lsmc;
    private javax.swing.JFormattedTextField jFmtTelefone_Lsmc;
    private javax.swing.JLabel jLblBairro;
    private javax.swing.JLabel jLblCep;
    private javax.swing.JLabel jLblCodigo;
    private javax.swing.JLabel jLblCpf;
    private javax.swing.JLabel jLblEmail;
    private javax.swing.JLabel jLblFeedback;
    private javax.swing.JLabel jLblGenero;
    private javax.swing.JLabel jLblLicencaPokemon;
    private javax.swing.JLabel jLblNascimento;
    private javax.swing.JLabel jLblNivelSatisfacao;
    private javax.swing.JLabel jLblNome;
    private javax.swing.JLabel jLblNumeroCasa;
    private javax.swing.JLabel jLblPais;
    private javax.swing.JLabel jLblRg;
    private javax.swing.JLabel jLblRua;
    private javax.swing.JLabel jLblTelefone;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTxtBairro_Lsmc;
    private javax.swing.JTextField jTxtCodigo_Lsmc;
    private javax.swing.JTextField jTxtEmail_Lsmc;
    private javax.swing.JTextArea jTxtFeedback_Lsmc;
    private javax.swing.JTextField jTxtNome_Lsmc;
    private javax.swing.JTextField jTxtNumeroCasa_Lsmc;
    private javax.swing.JTextField jTxtPais_Lsmc;
    private javax.swing.JTextField jTxtRua_Lsmc;
    // End of variables declaration//GEN-END:variables
}
