/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

//import BEAN.vendedor_lsmc;
//import DAO.vendedorDAO_lsmc;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author u08652975175
 */
public class JDlgVendedor extends javax.swing.JDialog {

    private MaskFormatter mascaraCpf, mascaraRg, mascaraData, mascaraTelefone;
    
    /**
     * Creates new form JDlgUsuarios
     */
    public JDlgVendedor(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Cadastro de Vendedores");
        setLocationRelativeTo(null);
//        habilitar(false);
        try {
            mascaraCpf = new MaskFormatter("###.###.###-##");
            mascaraRg = new MaskFormatter("#.###.###");
            mascaraData = new MaskFormatter("##/##/####");
            mascaraTelefone = new MaskFormatter("(##)####-####");
        } catch (ParseException ex) {
            Logger.getLogger(JDlgVendedor.class.getName()).log(Level.SEVERE, null, ex);
        }
        jFmtCpf_Lsmc.setFormatterFactory(new DefaultFormatterFactory(mascaraCpf));
        jFmtDataContrato_Lsmc.setFormatterFactory(new DefaultFormatterFactory(mascaraData));
        jFmtDataNascimento_Lsmc.setFormatterFactory(new DefaultFormatterFactory(mascaraData));
        jFmtRg_Lsmc.setFormatterFactory(new DefaultFormatterFactory(mascaraRg));
        jFmtTelefone_Lsmc.setFormatterFactory(new DefaultFormatterFactory(mascaraTelefone));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTxtCodigo_Lsmc = new javax.swing.JTextField();
        jTxtNome_Lsmc = new javax.swing.JTextField();
        jFmtCpf_Lsmc = new javax.swing.JFormattedTextField();
        jLblCodigo = new javax.swing.JLabel();
        jLblNome = new javax.swing.JLabel();
        jLblDataNascimento = new javax.swing.JLabel();
        jLblCpf = new javax.swing.JLabel();
        jBtnIncluir = new javax.swing.JButton();
        jBtnAlterar = new javax.swing.JButton();
        jBtnExcluir = new javax.swing.JButton();
        jBtnConfirmar = new javax.swing.JButton();
        jBtnCancelar = new javax.swing.JButton();
        jBtnPesquisar = new javax.swing.JButton();
        jLblRg = new javax.swing.JLabel();
        jLabelEndereco = new javax.swing.JLabel();
        jTxtEndereco_Lsmc = new javax.swing.JTextField();
        jFmtRg_Lsmc = new javax.swing.JFormattedTextField();
        jLblTelefone = new javax.swing.JLabel();
        jLblDataContrato = new javax.swing.JLabel();
        jLblEmail = new javax.swing.JLabel();
        jTxtEmail_Lsmc = new javax.swing.JTextField();
        jFmtDataContrato_Lsmc = new javax.swing.JFormattedTextField();
        jFmtTelefone_Lsmc = new javax.swing.JFormattedTextField();
        jLblFeedback = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTxtFeedback_Lsmc = new javax.swing.JTextArea();
        jFmtDataNascimento_Lsmc = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLblCodigo.setText("Código");

        jLblNome.setText("Nome");

        jLblDataNascimento.setText("Data de Nascimento");

        jLblCpf.setText("CPF");

        jBtnIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/incluir.png"))); // NOI18N
        jBtnIncluir.setText("Incluir");
        jBtnIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnIncluirActionPerformed(evt);
            }
        });

        jBtnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/alterar.png"))); // NOI18N
        jBtnAlterar.setText("Alterar");
        jBtnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAlterarActionPerformed(evt);
            }
        });

        jBtnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Excluir.png"))); // NOI18N
        jBtnExcluir.setText("Excluir");
        jBtnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExcluirActionPerformed(evt);
            }
        });

        jBtnConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/gravar.png"))); // NOI18N
        jBtnConfirmar.setText("Confirmar");
        jBtnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnConfirmarActionPerformed(evt);
            }
        });

        jBtnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancelar.png"))); // NOI18N
        jBtnCancelar.setText("Cancelar");
        jBtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelarActionPerformed(evt);
            }
        });

        jBtnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pesquisar.png"))); // NOI18N
        jBtnPesquisar.setText("Pesquisar");
        jBtnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPesquisarActionPerformed(evt);
            }
        });

        jLblRg.setText("RG");

        jLabelEndereco.setText("Endereço");

        jLblTelefone.setText("Telefone");

        jLblDataContrato.setText("Data de Contrato");

        jLblEmail.setText("Email");

        jLblFeedback.setText("Feedback");

        jTxtFeedback_Lsmc.setColumns(20);
        jTxtFeedback_Lsmc.setRows(5);
        jScrollPane1.setViewportView(jTxtFeedback_Lsmc);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLblFeedback)
                            .addComponent(jLblCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jBtnIncluir, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jBtnConfirmar))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jBtnCancelar)
                                    .addComponent(jBtnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jBtnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jBtnPesquisar))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jFmtDataNascimento_Lsmc)
                            .addComponent(jScrollPane1)
                            .addComponent(jTxtEndereco_Lsmc)
                            .addComponent(jLblEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTxtNome_Lsmc)
                            .addComponent(jTxtCodigo_Lsmc, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabelEndereco)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jFmtCpf_Lsmc, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLblCpf))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLblRg)
                                                .addGap(110, 227, Short.MAX_VALUE))
                                            .addComponent(jFmtRg_Lsmc)))
                                    .addComponent(jLblNome)
                                    .addComponent(jLblDataNascimento)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLblTelefone)
                                            .addComponent(jFmtTelefone_Lsmc, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLblDataContrato)
                                                .addGap(61, 152, Short.MAX_VALUE))
                                            .addComponent(jFmtDataContrato_Lsmc))))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jTxtEmail_Lsmc))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLblCodigo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtCodigo_Lsmc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLblNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtNome_Lsmc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLblDataNascimento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jFmtDataNascimento_Lsmc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblRg)
                    .addComponent(jLblCpf))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFmtRg_Lsmc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFmtCpf_Lsmc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(jLabelEndereco)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtEndereco_Lsmc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblTelefone)
                    .addComponent(jLblDataContrato))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFmtTelefone_Lsmc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFmtDataContrato_Lsmc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLblEmail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtEmail_Lsmc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLblFeedback)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnIncluir)
                    .addComponent(jBtnAlterar)
                    .addComponent(jBtnExcluir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnCancelar)
                    .addComponent(jBtnPesquisar)
                    .addComponent(jBtnConfirmar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnIncluirActionPerformed
        habilitar(true);
    }//GEN-LAST:event_jBtnIncluirActionPerformed

    private void jBtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelarActionPerformed
        habilitar(false);
    }//GEN-LAST:event_jBtnCancelarActionPerformed

    private void jBtnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExcluirActionPerformed
//        JOptionPane.showMessageDialog(null, "Exclusão");
//          int resp = JOptionPane.showConfirmDialog(null, "Confirma Exclusão", "Deletar Registro", JOptionPane.YES_NO_OPTION);
//          if (resp == JOptionPane.YES_OPTION){
//                vendedor_lsmc vendedor = new vendedor_lsmc();
//                int cod = Integer.valueOf(jTxtCodigo_Lsmc.getText());
//                vendedor.setIdVendedor_lsmc(cod);
//                vendedor.setNome_lsmc(jTxtNome_Lsmc.getText());
//                vendedor.setDataNasc_lsmc(null);
//                vendedor.setCpf_lsmc(jFmtCpf_Lsmc.getText());
//                vendedor.setRg_lsmc(jFmtRg_Lsmc.getText());
//                vendedor.setEndereco_lsmc(jTxtEndereco_Lsmc.getText());
//                vendedor.setTelefone_lsmc(jFmtTelefone_Lsmc.getText());
//                vendedor.setDataContrato_lsmc(null);
//                vendedor.setEmail_lsmc(jTxtEmail_Lsmc.getText());
//                vendedor.setFeedback_lsmc(jTxtFeedback_Lsmc.getText());
//
//                vendedorDAO_lsmc vendedorDAO = new vendedorDAO_lsmc();
//                vendedorDAO.delete(vendedor);
//              
//                JOptionPane.showMessageDialog(null, "Exclusão Ok!");
//                limpar();
//          }
    }//GEN-LAST:event_jBtnExcluirActionPerformed

    private void jBtnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPesquisarActionPerformed
//        String resp = JOptionPane.showInputDialog(null, "Entre com o Código de Vendedor");
//        if(resp == null) {
//            JOptionPane.showMessageDialog(null, "Código em branco");
//        } else {
//            vendedorDAO_lsmc vendedorDAO = new vendedorDAO_lsmc();
//            int cod = Integer.valueOf(resp);
//            vendedor_lsmc vendedor = (vendedor_lsmc) vendedorDAO.list(cod);
//            String cad = String.valueOf(vendedor.getIdVendedor_lsmc());
//            jTxtCodigo_Lsmc.setText(cad);
//            jTxtNome_Lsmc.setText(vendedor.getNome_lsmc());
//            jFmtDataNascimento_Lsmc.setText(null);
//            jFmtCpf_Lsmc.setText(vendedor.getCpf_lsmc());
//            jFmtRg_Lsmc.setText(vendedor.getRg_lsmc());
//            jTxtEndereco_Lsmc.setText(vendedor.getEndereco_lsmc());
//            jFmtTelefone_Lsmc.setText(vendedor.getTelefone_lsmc());
//            jFmtDataContrato_Lsmc.setText(null);
//            jTxtEmail_Lsmc.setText(vendedor.getEmail_lsmc());
//            jTxtFeedback_Lsmc.setText(vendedor.getFeedback_lsmc());
//        }
    }//GEN-LAST:event_jBtnPesquisarActionPerformed

    private void jBtnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAlterarActionPerformed
        JOptionPane.showMessageDialog(null, "Alterado com sucesso!");
    }//GEN-LAST:event_jBtnAlterarActionPerformed

    private void jBtnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnConfirmarActionPerformed
//        vendedor_lsmc vendedor = new vendedor_lsmc();
//        int cod = Integer.valueOf(jTxtCodigo_Lsmc.getText());
//        vendedor.setIdVendedor_lsmc(cod);
//        vendedor.setNome_lsmc(jTxtNome_Lsmc.getText());
//        vendedor.setDataNasc_lsmc(null);
//        vendedor.setCpf_lsmc(jFmtCpf_Lsmc.getText());
//        vendedor.setRg_lsmc(jFmtRg_Lsmc.getText());
//        vendedor.setEndereco_lsmc(jTxtEndereco_Lsmc.getText());
//        vendedor.setTelefone_lsmc(jFmtTelefone_Lsmc.getText());
//        vendedor.setDataContrato_lsmc(null);
//        vendedor.setEmail_lsmc(jTxtEmail_Lsmc.getText());
//        vendedor.setFeedback_lsmc(jTxtFeedback_Lsmc.getText());
//
//        vendedorDAO_lsmc vendedorDAO = new vendedorDAO_lsmc();
//        vendedorDAO.insert(vendedor);
//        habilitar(false);
//        
//        JOptionPane.showMessageDialog(null, "Vendedor Cadastrado!");
//        limpar();
    }//GEN-LAST:event_jBtnConfirmarActionPerformed
    
    private void habilitar(boolean valor){
//        jTxtCodigo_Lsmc.setEnabled(valor);
//        jTxtNome_Lsmc.setEnabled(valor);
//        jFmtDataNascimento_Lsmc.setEnabled(valor);
//        jTxtFeedback_Lsmc.setEnabled(valor);
//        jFmtCpf_Lsmc.setEnabled(valor);
//        jFmtRg_Lsmc.setEnabled(valor);
//        jFmtDataContrato_Lsmc.setEnabled(valor);
//        jFmtTelefone_Lsmc.setEnabled(valor);
//        jTxtEndereco_Lsmc.setEnabled(valor);
//        jTxtEmail_Lsmc.setEnabled(valor);
//        jBtnCancelar.setEnabled(valor);
//        jBtnConfirmar.setEnabled(valor);
//        
//        jBtnIncluir.setEnabled(!valor);
//        jBtnAlterar.setEnabled(!valor);
//        jBtnExcluir.setEnabled(!valor);
//        jBtnPesquisar.setEnabled(!valor);
    }
    
    public void limpar() {
//        jTxtCodigo_Lsmc.setText("");
//        jTxtNome_Lsmc.setText("");
//        jFmtDataNascimento_Lsmc.setText("");
//        jTxtFeedback_Lsmc.setText("");
//        jFmtCpf_Lsmc.setText("");
//        jFmtRg_Lsmc.setText("");
//        jFmtDataContrato_Lsmc.setText("");
//        jFmtTelefone_Lsmc.setText("");
//        jTxtEndereco_Lsmc.setText("");
//        jTxtEmail_Lsmc.setText("");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgVendedor dialog = new JDlgVendedor(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAlterar;
    private javax.swing.JButton jBtnCancelar;
    private javax.swing.JButton jBtnConfirmar;
    private javax.swing.JButton jBtnExcluir;
    private javax.swing.JButton jBtnIncluir;
    private javax.swing.JButton jBtnPesquisar;
    private javax.swing.JFormattedTextField jFmtCpf_Lsmc;
    private javax.swing.JFormattedTextField jFmtDataContrato_Lsmc;
    private javax.swing.JFormattedTextField jFmtDataNascimento_Lsmc;
    private javax.swing.JFormattedTextField jFmtRg_Lsmc;
    private javax.swing.JFormattedTextField jFmtTelefone_Lsmc;
    private javax.swing.JLabel jLabelEndereco;
    private javax.swing.JLabel jLblCodigo;
    private javax.swing.JLabel jLblCpf;
    private javax.swing.JLabel jLblDataContrato;
    private javax.swing.JLabel jLblDataNascimento;
    private javax.swing.JLabel jLblEmail;
    private javax.swing.JLabel jLblFeedback;
    private javax.swing.JLabel jLblNome;
    private javax.swing.JLabel jLblRg;
    private javax.swing.JLabel jLblTelefone;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTxtCodigo_Lsmc;
    private javax.swing.JTextField jTxtEmail_Lsmc;
    private javax.swing.JTextField jTxtEndereco_Lsmc;
    private javax.swing.JTextArea jTxtFeedback_Lsmc;
    private javax.swing.JTextField jTxtNome_Lsmc;
    // End of variables declaration//GEN-END:variables
}
