/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

//import BEAN.pokemon_lsmc;
//import DAO.pokemonDAO_lsmc;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author u08652975175
 */
public class JDlgPokemon extends javax.swing.JDialog {
    
    /**
     * Creates new form JDlgUsuarios
     */
    public JDlgPokemon(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Cadastro de Pokémon");
        setLocationRelativeTo(null);
        habilitar(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTxtCodigo_Lsmc = new javax.swing.JTextField();
        jTxtNome_Lsmc = new javax.swing.JTextField();
        jFmtTamanho_Lsmc = new javax.swing.JFormattedTextField();
        jFmtPeso_Lsmc = new javax.swing.JFormattedTextField();
        jLblCodigo = new javax.swing.JLabel();
        jLblNome = new javax.swing.JLabel();
        jLblTipo = new javax.swing.JLabel();
        jLblTamanho = new javax.swing.JLabel();
        jLblPeso = new javax.swing.JLabel();
        jLblPreco = new javax.swing.JLabel();
        jBtnIncluir = new javax.swing.JButton();
        jBtnAlterar = new javax.swing.JButton();
        jBtnExcluir = new javax.swing.JButton();
        jBtnConfirmar = new javax.swing.JButton();
        jBtnCancelar = new javax.swing.JButton();
        jBtnPesquisar = new javax.swing.JButton();
        jFmtPreco_Lsmc = new javax.swing.JFormattedTextField();
        jLblEspecie = new javax.swing.JLabel();
        jTxtEspecie_Lsmc = new javax.swing.JTextField();
        jCboTipo_lsmc = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLblCodigo.setText("Código");

        jLblNome.setText("Nome");

        jLblTipo.setText("Tipo");

        jLblTamanho.setText("Tamanho");

        jLblPeso.setText("Peso");

        jLblPreco.setText("Preço");

        jBtnIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/incluir.png"))); // NOI18N
        jBtnIncluir.setText("Incluir");
        jBtnIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnIncluirActionPerformed(evt);
            }
        });

        jBtnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/alterar.png"))); // NOI18N
        jBtnAlterar.setText("Alterar");
        jBtnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAlterarActionPerformed(evt);
            }
        });

        jBtnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Excluir.png"))); // NOI18N
        jBtnExcluir.setText("Excluir");
        jBtnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExcluirActionPerformed(evt);
            }
        });

        jBtnConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/gravar.png"))); // NOI18N
        jBtnConfirmar.setText("Confirmar");
        jBtnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnConfirmarActionPerformed(evt);
            }
        });

        jBtnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancelar.png"))); // NOI18N
        jBtnCancelar.setText("Cancelar");
        jBtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelarActionPerformed(evt);
            }
        });

        jBtnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pesquisar.png"))); // NOI18N
        jBtnPesquisar.setText("Pesquisar");
        jBtnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPesquisarActionPerformed(evt);
            }
        });

        jLblEspecie.setText("Espécie");

        jCboTipo_lsmc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Normal", "Fogo", "Água", "Grama", "Voador", "Lutador", "Veneno", "Elétrico", "Terra", "Pedra", "Psíquico", "Gelo", "Inseto", "Fantasma", "Ferro", "Dragão", "Sombrio", "Fada" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLblTipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLblNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTxtCodigo_Lsmc)
                            .addComponent(jTxtNome_Lsmc)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLblCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jBtnConfirmar)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jBtnCancelar))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jBtnIncluir, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jBtnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jBtnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jBtnPesquisar))))
                                .addGap(0, 6, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jFmtTamanho_Lsmc)
                                    .addComponent(jFmtPreco_Lsmc)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLblTamanho)
                                            .addComponent(jLblPreco))
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLblPeso)
                                    .addComponent(jFmtPeso_Lsmc, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                    .addComponent(jLblEspecie)
                                    .addComponent(jTxtEspecie_Lsmc))))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jCboTipo_lsmc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLblCodigo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtCodigo_Lsmc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLblNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtNome_Lsmc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLblTipo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCboTipo_lsmc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblTamanho)
                    .addComponent(jLblPeso))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFmtPeso_Lsmc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFmtTamanho_Lsmc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblPreco)
                    .addComponent(jLblEspecie))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFmtPreco_Lsmc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtEspecie_Lsmc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnExcluir)
                    .addComponent(jBtnAlterar)
                    .addComponent(jBtnIncluir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnConfirmar)
                    .addComponent(jBtnCancelar)
                    .addComponent(jBtnPesquisar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnIncluirActionPerformed
        habilitar(true);
    }//GEN-LAST:event_jBtnIncluirActionPerformed

    private void jBtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelarActionPerformed
        habilitar(false);
    }//GEN-LAST:event_jBtnCancelarActionPerformed

    private void jBtnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExcluirActionPerformed
//        JOptionPane.showMessageDialog(null, "Exclusão");
//          int resp = JOptionPane.showConfirmDialog(null, "Confirma Exclusão", "Deletar Registro", JOptionPane.YES_NO_OPTION);
//          if (resp == JOptionPane.YES_OPTION){
//            pokemon_lsmc pokemon = new pokemon_lsmc();
//            int cod = Integer.valueOf(jTxtCodigo_Lsmc.getText());
//            pokemon.setIdPokemon_lsmc(cod);
//            pokemon.setNome_lsmc(jTxtNome_Lsmc.getText());
//            pokemon.setTipo_lsmc(jCboTipo_lsmc.getSelectedIndex());
//            pokemon.setTamanho_lsmc(jFmtTamanho_Lsmc.getText());
//            pokemon.setPeso_lsmc(jFmtPeso_Lsmc.getText());
//            pokemon.setPreco_lsmc(jFmtPreco_Lsmc.getText());
//            pokemon.setEspecie_lsmc(jTxtEspecie_Lsmc.getText());
//
//            pokemonDAO_lsmc pokemonDAO = new pokemonDAO_lsmc();
//            pokemonDAO.delete(pokemon);
//              
//            JOptionPane.showMessageDialog(null, "Exclusão Ok!");
//            limpar();
//          }
    }//GEN-LAST:event_jBtnExcluirActionPerformed

    private void jBtnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPesquisarActionPerformed
//        String resp = JOptionPane.showInputDialog(null, "Entre com o Código de Pokemon");
//        if(resp == null) {
//            JOptionPane.showMessageDialog(null, "Código em branco");
//        } else {
//            pokemonDAO_lsmc pokemonDAO = new pokemonDAO_lsmc();
//            int cod = Integer.valueOf(resp);
//            pokemon_lsmc pokemon = (pokemon_lsmc) pokemonDAO.list(cod);
//            String cad = String.valueOf(pokemon.getIdPokemon_lsmc());
//            jTxtCodigo_Lsmc.setText(cad);
//            jTxtNome_Lsmc.setText(pokemon.getNome_lsmc());
//            jCboTipo_lsmc.setSelectedIndex(pokemon.getTipo_lsmc());
//            jFmtTamanho_Lsmc.setText(pokemon.getTamanho_lsmc());
//            jFmtPeso_Lsmc.setText(pokemon.getPeso_lsmc());
//            jFmtPreco_Lsmc.setText(pokemon.getPreco_lsmc());
//            jTxtEspecie_Lsmc.setText(pokemon.getEspecie_lsmc());
//        }
    }//GEN-LAST:event_jBtnPesquisarActionPerformed

    private void jBtnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAlterarActionPerformed
        JOptionPane.showMessageDialog(null, "Alterado com sucesso!");
    }//GEN-LAST:event_jBtnAlterarActionPerformed

    private void jBtnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnConfirmarActionPerformed
//        pokemon_lsmc pokemon = new pokemon_lsmc();
//        int cod = Integer.valueOf(jTxtCodigo_Lsmc.getText());
//        pokemon.setIdPokemon_lsmc(cod);
//        pokemon.setNome_lsmc(jTxtNome_Lsmc.getText());
//        pokemon.setTipo_lsmc(jCboTipo_lsmc.getSelectedIndex());
//        pokemon.setTamanho_lsmc(jFmtTamanho_Lsmc.getText());
//        pokemon.setPeso_lsmc(jFmtPeso_Lsmc.getText());
//        pokemon.setPreco_lsmc(jFmtPreco_Lsmc.getText());
//        pokemon.setEspecie_lsmc(jTxtEspecie_Lsmc.getText());
//
//        pokemonDAO_lsmc pokemonDAO = new pokemonDAO_lsmc();
//        pokemonDAO.insert(pokemon);
//        habilitar(false);
//        
//        JOptionPane.showMessageDialog(null, "Pokemon Cadastrado!");
//        limpar();
    }//GEN-LAST:event_jBtnConfirmarActionPerformed
    
    private void habilitar(boolean valor){
//        jTxtCodigo_Lsmc.setEnabled(valor);
//        jTxtNome_Lsmc.setEnabled(valor);
//        jCboTipo_lsmc.setEnabled(valor);
//        jTxtEspecie_Lsmc.setEnabled(valor);
//        jFmtTamanho_Lsmc.setEnabled(valor);
//        jFmtPeso_Lsmc.setEnabled(valor);
//        jFmtPreco_Lsmc.setEnabled(valor);
//        jBtnCancelar.setEnabled(valor);
//        jBtnConfirmar.setEnabled(valor);
//        
//        jBtnIncluir.setEnabled(!valor);
//        jBtnAlterar.setEnabled(!valor);
//        jBtnExcluir.setEnabled(!valor);
//        jBtnPesquisar.setEnabled(!valor);
    }
    
    private void limpar(){
//        jTxtCodigo_Lsmc.setText("");
//        jTxtNome_Lsmc.setText("");
//        jCboTipo_lsmc.setSelectedIndex(-1);
//        jTxtEspecie_Lsmc.setText("");
//        jFmtTamanho_Lsmc.setText("");
//        jFmtPeso_Lsmc.setText("");
//        jFmtPreco_Lsmc.setText("");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgPokemon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgPokemon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgPokemon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgPokemon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgPokemon dialog = new JDlgPokemon(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAlterar;
    private javax.swing.JButton jBtnCancelar;
    private javax.swing.JButton jBtnConfirmar;
    private javax.swing.JButton jBtnExcluir;
    private javax.swing.JButton jBtnIncluir;
    private javax.swing.JButton jBtnPesquisar;
    private javax.swing.JComboBox<String> jCboTipo_lsmc;
    private javax.swing.JFormattedTextField jFmtPeso_Lsmc;
    private javax.swing.JFormattedTextField jFmtPreco_Lsmc;
    private javax.swing.JFormattedTextField jFmtTamanho_Lsmc;
    private javax.swing.JLabel jLblCodigo;
    private javax.swing.JLabel jLblEspecie;
    private javax.swing.JLabel jLblNome;
    private javax.swing.JLabel jLblPeso;
    private javax.swing.JLabel jLblPreco;
    private javax.swing.JLabel jLblTamanho;
    private javax.swing.JLabel jLblTipo;
    private javax.swing.JTextField jTxtCodigo_Lsmc;
    private javax.swing.JTextField jTxtEspecie_Lsmc;
    private javax.swing.JTextField jTxtNome_Lsmc;
    // End of variables declaration//GEN-END:variables
}
